In [1]:
from ngram_model.ngn import NgramNetwork

/Users/edi/dev/ai/character-language-model/.venv/lib/python3.14/site-packages/torch/_subclasses/functional_tensor.py:283: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
network = NgramNetwork('data/hungarian_cities_3000.csv')

In [ ]:

chunk_size = 2
for i in range(20):
    network.train(chunk_size=chunk_size, rate=0.1)

tensor([4.6525], grad_fn=<DivBackward0>)
tensor([4.6518], grad_fn=<DivBackward0>)
tensor([4.6512], grad_fn=<DivBackward0>)
tensor([4.6504], grad_fn=<DivBackward0>)
tensor([4.6495], grad_fn=<DivBackward0>)
tensor([4.6486], grad_fn=<DivBackward0>)
tensor([4.6480], grad_fn=<DivBackward0>)
tensor([4.6472], grad_fn=<DivBackward0>)
tensor([4.6465], grad_fn=<DivBackward0>)
tensor([4.6458], grad_fn=<DivBackward0>)
tensor([4.6450], grad_fn=<DivBackward0>)
tensor([4.6444], grad_fn=<DivBackward0>)
tensor([4.6434], grad_fn=<DivBackward0>)
tensor([4.6426], grad_fn=<DivBackward0>)
tensor([4.6419], grad_fn=<DivBackward0>)
tensor([4.6413], grad_fn=<DivBackward0>)
tensor([4.6404], grad_fn=<DivBackward0>)
tensor([4.6396], grad_fn=<DivBackward0>)
tensor([4.6390], grad_fn=<DivBackward0>)
tensor([4.6381], grad_fn=<DivBackward0>)


In [10]:
out = ['<begin>']
while True:
    out.append(
        network.tokenizer.decode(
            network.sample(
                network.tokenizer.encode(out[-chunk_size:])
            )
        )
    )
    

    if out[-1] == '<end>':
        break
print(''.join(out))

<begin> LGúku2sÉONÓŐö7űrFtzMÁpD9DdyuoÖ9tzÁ ufb<begin><begin>J5R.vHrMFHHUEH1lÚuKiTBf432ŐDAFEU.c<end>
